name: Lint

on:
  push:
    branches:
      - v2
  pull_request:

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Lint
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: v2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_PYINK: false
